/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as TranslateRouteImport } from './routes/translate'
import { Route as WorksheetsRouteImport } from './routes/worksheets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslateRoute = TranslateRouteImport.update({
  id: '/translate',
  path: '/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksheetsRoute = WorksheetsRouteImport.update({
  id: '/worksheets',
  path: '/worksheets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/progress': typeof ProgressRoute
  '/translate': typeof TranslateRoute
  '/worksheets': typeof WorksheetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/progress': typeof ProgressRoute
  '/translate': typeof TranslateRoute
  '/worksheets': typeof WorksheetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library': typeof LibraryRoute
  '/live': typeof LiveRoute
  '/progress': typeof ProgressRoute
  '/translate': typeof TranslateRoute
  '/worksheets': typeof WorksheetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/library' | '/live' | '/progress' | '/translate' | '/worksheets'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library' | '/live' | '/progress' | '/translate' | '/worksheets'
  id:
    | '__root__'
    | '/'
    | '/library'
    | '/live'
    | '/progress'
    | '/translate'
    | '/worksheets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryRoute: typeof LibraryRoute
  LiveRoute: typeof LiveRoute
  ProgressRoute: typeof ProgressRoute
  TranslateRoute: typeof TranslateRoute
  WorksheetsRoute: typeof WorksheetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worksheets': {
      id: '/worksheets'
      path: '/worksheets'
      fullPath: '/worksheets'
      preLoaderRoute: typeof WorksheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryRoute: LibraryRoute,
  LiveRoute: LiveRoute,
  ProgressRoute: ProgressRoute,
  TranslateRoute: TranslateRoute,
  WorksheetsRoute: WorksheetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
